language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11 

cache:
  directories:
  - $HOME/.m2
  
script:
  - mvn -B clean package 
  
after_success:
  - mvn -B clean verify jacoco:report jacoco:report-integration coveralls:report
