jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  
language: java
cache:
  directories:
  - $HOME/.m2
  
script:
  - mvn clean package
  
after_success:
  - mvn clean verify jacoco:report jacoco:report-integration coveralls:report
